package com.abdulkus.essentialremap.ui

/**
 * App-wide translations for the compact EN/RU source strings used by the UI.
 * English is the fallback so newly added text never renders blank.
 * Order in each entry: DE, FR, PL, UA, IN, CH, JP, KO.
 */
internal fun AppLanguage.translate(en: String, ru: String): String {
    if (this == AppLanguage.ENGLISH) return en
    if (this == AppLanguage.RUSSIAN) return ru
    dynamicTranslation(en)?.let { return it }
    val index = when (this) {
        AppLanguage.GERMAN -> 0
        AppLanguage.FRENCH -> 1
        AppLanguage.POLISH -> 2
        AppLanguage.UKRAINIAN -> 3
        AppLanguage.INDONESIAN -> 4
        AppLanguage.CHINESE -> 5
        AppLanguage.JAPANESE -> 6
        AppLanguage.KOREAN -> 7
        else -> return en
    }
    return translations[en]?.getOrNull(index) ?: en
}

private fun AppLanguage.dynamicTranslation(en: String): String? {
    if (en.startsWith("Update ") && en.endsWith(" is available")) {
        val version = en.removePrefix("Update ").removeSuffix(" is available")
        return when (this) {
            AppLanguage.GERMAN -> "Update $version ist verfügbar"
            AppLanguage.FRENCH -> "La mise à jour $version est disponible"
            AppLanguage.POLISH -> "Dostępna jest aktualizacja $version"
            AppLanguage.UKRAINIAN -> "Доступне оновлення $version"
            AppLanguage.INDONESIAN -> "Pembaruan $version tersedia"
            AppLanguage.CHINESE -> "发现更新 $version"
            AppLanguage.JAPANESE -> "アップデート $version を利用できます"
            AppLanguage.KOREAN -> "업데이트 $version 사용 가능"
            else -> null
        }
    }
    val prefix = "Another key remapper is active: "
    val suffix = ". Disable its Essential Key rule to avoid duplicate actions."
    if (en.startsWith(prefix) && en.endsWith(suffix)) {
        val names = en.removePrefix(prefix).removeSuffix(suffix)
        return when (this) {
            AppLanguage.GERMAN -> "Ein anderer Tasten-Remapper ist aktiv: $names. Deaktiviere dort die Essential-Key-Regel, um doppelte Aktionen zu vermeiden."
            AppLanguage.FRENCH -> "Un autre remappeur de touches est actif : $names. Désactivez sa règle Essential Key pour éviter les actions en double."
            AppLanguage.POLISH -> "Aktywny jest inny remapper przycisków: $names. Wyłącz w nim regułę Essential Key, aby uniknąć podwójnych akcji."
            AppLanguage.UKRAINIAN -> "Активний інший перепризначувач кнопок: $names. Вимкніть у ньому правило Essential Key, щоб уникнути дублювання дій."
            AppLanguage.INDONESIAN -> "Aplikasi pemetaan tombol lain sedang aktif: $names. Nonaktifkan aturan Essential Key di sana agar tindakan tidak berjalan dua kali."
            AppLanguage.CHINESE -> "另一个按键映射应用正在运行：$names。请关闭其中的 Essential Key 规则，以免重复执行操作。"
            AppLanguage.JAPANESE -> "別のキーリマップアプリが有効です: $names。操作の重複を防ぐため、そのアプリの Essential Key ルールを無効にしてください。"
            AppLanguage.KOREAN -> "다른 키 리매퍼가 활성화되어 있습니다: $names. 동작이 중복되지 않도록 해당 앱의 Essential Key 규칙을 꺼 주세요."
            else -> null
        }
    }
    return null
}

private fun a(de: String, fr: String, pl: String, ua: String, ind: String, ch: String, jp: String, ko: String) =
    arrayOf(de, fr, pl, ua, ind, ch, jp, ko)

private val translations = mapOf(
    "Restart the sleep monitor to handle Essential Key while the display is off." to a("Starte den Ruhemodus-Monitor neu, damit Essential Key bei ausgeschaltetem Display funktioniert.", "Redémarrez le moniteur de veille pour utiliser Essential Key lorsque l’écran est éteint.", "Uruchom ponownie monitor uśpienia, aby Essential Key działał przy wyłączonym ekranie.", "Перезапустіть монітор сну, щоб Essential Key працювала при вимкненому екрані.", "Mulai ulang monitor tidur agar Essential Key berfungsi saat layar mati.", "请重新启动休眠监视器，以便在熄屏时使用 Essential Key。", "画面オフ時に Essential Key を使うにはスリープモニターを再起動してください。", "화면이 꺼진 상태에서 Essential Key를 사용하려면 절전 모니터를 다시 시작하세요."),
    "Grant Do Not Disturb access first" to a("Zuerst Zugriff auf „Nicht stören“ erlauben", "Autorisez d’abord l’accès à « Ne pas déranger »", "Najpierw zezwól na dostęp do trybu Nie przeszkadzać", "Спочатку надайте доступ до режиму «Не турбувати»", "Izinkan akses Jangan Ganggu terlebih dahulu", "请先授予“勿扰模式”访问权限", "先に「サイレント モード」へのアクセスを許可してください", "먼저 방해 금지 모드 접근 권한을 허용하세요"),
    "Wireless debugging is already enabled. Reconnecting with the saved key…" to a("Wireless-Debugging ist bereits aktiviert. Verbindung mit dem gespeicherten Schlüssel wird wiederhergestellt…", "Le débogage sans fil est déjà activé. Reconnexion avec la clé enregistrée…", "Debugowanie bezprzewodowe jest już włączone. Ponowne łączenie zapisanym kluczem…", "Wireless debugging уже ввімкнено. Повторне підключення збереженим ключем…", "Wireless debugging sudah aktif. Menyambungkan kembali dengan kunci tersimpan…", "无线调试已开启，正在使用已保存的密钥重新连接…", "ワイヤレスデバッグはすでに有効です。保存済みのキーで再接続しています…", "무선 디버깅이 이미 켜져 있습니다. 저장된 키로 다시 연결하는 중…"),
    "BACK" to a("ZURÜCK", "RETOUR", "WSTECZ", "НАЗАД", "KEMBALI", "返回", "戻る", "뒤로"),
    "DONE" to a("FERTIG", "TERMINÉ", "GOTOWE", "ГОТОВО", "SELESAI", "完成", "完了", "완료"),
    "NEXT" to a("WEITER", "SUIVANT", "DALEJ", "ДАЛІ", "LANJUT", "下一步", "次へ", "다음"),
    "Choose setup mode" to a("Einrichtungsmodus wählen", "Choisir le mode de configuration", "Wybierz tryb konfiguracji", "Оберіть режим роботи", "Pilih mode penyiapan", "选择设置模式", "セットアップ方法を選択", "설정 모드 선택"),
    "You can change this later in Settings." to a("Das kannst du später in den Einstellungen ändern.", "Vous pourrez modifier ce choix plus tard dans les paramètres.", "Możesz to później zmienić w ustawieniach.", "Це можна змінити пізніше в налаштуваннях.", "Anda dapat mengubahnya nanti di Pengaturan.", "稍后可在设置中更改。", "後から設定で変更できます。", "나중에 설정에서 변경할 수 있습니다."),
    "Screen on" to a("Nur bei eingeschaltetem Display", "Écran allumé", "Tylko włączony ekran", "Лише увімкнений екран", "Layar menyala", "仅亮屏", "画面オンのみ", "화면 켜짐"),
    "Simpler setup. Nothing needs to be reactivated after a phone reboot." to a("Einfachere Einrichtung. Nach einem Neustart muss nichts erneut aktiviert werden.", "Configuration plus simple. Rien ne doit être réactivé après le redémarrage du téléphone.", "Prostsza konfiguracja. Po ponownym uruchomieniu telefonu niczego nie trzeba ponownie aktywować.", "Простіше налаштування. Після перезавантаження телефону нічого не потрібно активувати повторно.", "Penyiapan lebih sederhana. Tidak perlu mengaktifkan ulang apa pun setelah ponsel dimulai ulang.", "设置更简单，手机重启后无需重新启用任何内容。", "簡単なセットアップです。端末の再起動後に再有効化する必要はありません。", "더 간단한 설정입니다. 휴대폰 재부팅 후 다시 활성화할 필요가 없습니다."),
    "Screen on + off" to a("Display an + aus", "Écran allumé + éteint", "Ekran włączony + wyłączony", "Увімкнений + вимкнений екран", "Layar menyala + mati", "亮屏 + 熄屏", "画面オン + オフ", "화면 켜짐 + 꺼짐"),
    "Adds the sleep monitor. It must be restarted through Wireless debugging after every phone reboot." to a("Fügt den Ruhemodus-Monitor hinzu. Nach jedem Neustart muss er über Wireless-Debugging neu gestartet werden.", "Ajoute le moniteur de veille. Il doit être redémarré via le débogage sans fil après chaque redémarrage du téléphone.", "Dodaje monitor uśpienia. Po każdym ponownym uruchomieniu telefonu trzeba go uruchomić ponownie przez debugowanie bezprzewodowe.", "Додає монітор сну. Після кожного перезавантаження телефону його потрібно перезапускати через Wireless debugging.", "Menambahkan monitor tidur. Monitor harus dimulai ulang melalui Wireless debugging setiap kali ponsel dimulai ulang.", "启用休眠监视器。每次手机重启后都需要通过无线调试重新启动。", "スリープモニターを追加します。端末を再起動するたびにワイヤレスデバッグから再起動が必要です。", "절전 모니터를 추가합니다. 휴대폰을 재부팅할 때마다 무선 디버깅을 통해 다시 시작해야 합니다."),
    "VIDEO SETUP GUIDE" to a("VIDEO-ANLEITUNG", "GUIDE VIDÉO", "INSTRUKCJA WIDEO", "ВІДЕОІНСТРУКЦІЯ", "PANDUAN VIDEO", "视频设置指南", "動画セットアップガイド", "동영상 설정 가이드"),
    "Release Essential Key" to a("Essential Key freigeben", "Libérer Essential Key", "Zwolnij Essential Key", "Звільніть Essential Key", "Lepaskan Essential Key", "释放 Essential Key", "Essential Key を解放", "Essential Key 해제"),
    "Essential Remap disables the two Nothing components that currently own the button. Their data is kept and the change can be restored later." to a("Essential Remap deaktiviert die zwei Nothing-Komponenten, die die Taste derzeit verwenden. Ihre Daten bleiben erhalten und die Änderung kann später rückgängig gemacht werden.", "Essential Remap désactive les deux composants Nothing qui utilisent actuellement le bouton. Leurs données sont conservées et la modification peut être annulée plus tard.", "Essential Remap wyłącza dwa komponenty Nothing, które obecnie przechwytują przycisk. Ich dane zostają zachowane, a zmianę można później cofnąć.", "Essential Remap вимкне два компоненти Nothing, які зараз перехоплюють кнопку. Їхні дані збережуться, а зміну можна буде скасувати.", "Essential Remap menonaktifkan dua komponen Nothing yang saat ini menggunakan tombol. Datanya tetap tersimpan dan perubahan dapat dipulihkan nanti.", "Essential Remap 会禁用当前占用该按键的两个 Nothing 组件。数据会保留，之后可以恢复。", "Essential Remap は現在ボタンを使用している2つの Nothing コンポーネントを無効にします。データは保持され、後から元に戻せます。", "Essential Remap은 현재 버튼을 사용하는 두 Nothing 구성요소를 비활성화합니다. 데이터는 유지되며 나중에 복원할 수 있습니다."),
    "Essential Space and Essential Recorder" to a("Essential Space und Essential Recorder", "Essential Space et Essential Recorder", "Essential Space i Essential Recorder", "Essential Space та Essential Recorder", "Essential Space dan Essential Recorder", "Essential Space 和 Essential Recorder", "Essential Space と Essential Recorder", "Essential Space 및 Essential Recorder"),
    "RELEASE KEY" to a("TASTE FREIGEBEN", "LIBÉRER LE BOUTON", "ZWOLNIJ PRZYCISK", "ЗВІЛЬНИТИ КНОПКУ", "LEPASKAN TOMBOL", "释放按键", "ボタンを解放", "버튼 해제"),
    "Open developer options" to a("Entwickleroptionen öffnen", "Ouvrir les options développeur", "Otwórz opcje programisty", "Відкрити параметри розробника", "Buka opsi pengembang", "打开开发者选项", "開発者向けオプションを開く", "개발자 옵션 열기"),
    "Enable Essential Remap" to a("Essential Remap aktivieren", "Activer Essential Remap", "Włącz Essential Remap", "Увімкніть Essential Remap", "Aktifkan Essential Remap", "启用 Essential Remap", "Essential Remap を有効化", "Essential Remap 활성화"),
    "Accessibility lets the app receive the Essential Key while Android is in use. Essential Remap does not read screen content." to a("Die Bedienungshilfe erlaubt der App, die Essential Key während der Nutzung von Android zu empfangen. Essential Remap liest keine Bildschirminhalte.", "L’accessibilité permet à l’application de recevoir Essential Key pendant l’utilisation d’Android. Essential Remap ne lit pas le contenu de l’écran.", "Ułatwienia dostępu pozwalają aplikacji odbierać Essential Key podczas korzystania z Androida. Essential Remap nie odczytuje zawartości ekranu.", "Спеціальні можливості дозволяють застосунку отримувати натискання Essential Key під час роботи Android. Essential Remap не читає вміст екрана.", "Aksesibilitas memungkinkan aplikasi menerima Essential Key saat Android digunakan. Essential Remap tidak membaca isi layar.", "无障碍服务允许应用在使用 Android 时接收 Essential Key。Essential Remap 不读取屏幕内容。", "ユーザー補助により、Android 使用中に Essential Key を受け取れます。Essential Remap は画面内容を読み取りません。", "접근성 서비스를 통해 Android 사용 중 Essential Key 입력을 받을 수 있습니다. Essential Remap은 화면 내용을 읽지 않습니다."),
    "Service enabled" to a("Dienst aktiviert", "Service activé", "Usługa włączona", "Службу увімкнено", "Layanan aktif", "服务已启用", "サービス有効", "서비스 켜짐"),
    "Service disabled" to a("Dienst deaktiviert", "Service désactivé", "Usługa wyłączona", "Службу вимкнено", "Layanan nonaktif", "服务已关闭", "サービス無効", "서비스 꺼짐"),
    "Accessibility service is disabled" to a("Bedienungshilfe ist deaktiviert", "Le service d’accessibilité est désactivé", "Usługa ułatwień dostępu jest wyłączona", "Службу спеціальних можливостей вимкнено", "Layanan aksesibilitas nonaktif", "无障碍服务已关闭", "ユーザー補助サービスが無効です", "접근성 서비스가 꺼져 있습니다"),
    "Enable Essential Remap in Accessibility settings." to a("Aktiviere Essential Remap in den Bedienungshilfe-Einstellungen.", "Activez Essential Remap dans les paramètres d’accessibilité.", "Włącz Essential Remap w ustawieniach ułatwień dostępu.", "Увімкніть Essential Remap у налаштуваннях спеціальних можливостей.", "Aktifkan Essential Remap di pengaturan Aksesibilitas.", "请在无障碍设置中启用 Essential Remap。", "ユーザー補助設定で Essential Remap を有効にしてください。", "접근성 설정에서 Essential Remap을 켜 주세요."),
    "Required for remapping" to a("Für die Tastenbelegung erforderlich", "Nécessaire pour le remappage", "Wymagane do zmiany funkcji przycisku", "Потрібно для перепризначення", "Diperlukan untuk pemetaan ulang", "重新映射所必需", "リマップに必要", "키 재매핑에 필요"),
    "OPEN ACCESSIBILITY" to a("BEDIENUNGSHILFE ÖFFNEN", "OUVRIR L’ACCESSIBILITÉ", "OTWÓRZ UŁATWIENIA DOSTĘPU", "ВІДКРИТИ СПЕЦІАЛЬНІ МОЖЛИВОСТІ", "BUKA AKSESIBILITAS", "打开无障碍设置", "ユーザー補助を開く", "접근성 설정 열기"),
    "Enable screen-off handling" to a("Funktion bei ausgeschaltetem Display aktivieren", "Activer le fonctionnement écran éteint", "Włącz działanie przy wyłączonym ekranie", "Увімкніть роботу з вимкненим екраном", "Aktifkan saat layar mati", "启用熄屏处理", "画面オフ時の動作を有効化", "화면 꺼짐 동작 활성화"),
    "The sleep monitor runs with Android's shell privileges and listens only for Essential Key. It does not hold a wake lock. After a phone reboot it must be restarted." to a("Der Ruhemodus-Monitor läuft mit Android-Shell-Rechten und lauscht ausschließlich auf die Essential Key. Er hält keinen Wake-Lock. Nach einem Neustart muss er neu gestartet werden.", "Le moniteur de veille utilise les privilèges shell d’Android et n’écoute que Essential Key. Il ne maintient aucun wake lock. Il doit être redémarré après un redémarrage du téléphone.", "Monitor uśpienia działa z uprawnieniami powłoki Androida i nasłuchuje wyłącznie Essential Key. Nie utrzymuje blokady wybudzenia. Po restarcie telefonu trzeba go uruchomić ponownie.", "Монітор сну працює з правами Android shell і слухає лише Essential Key. Він не утримує wake lock. Після перезавантаження телефону його потрібно перезапустити.", "Monitor tidur berjalan dengan hak shell Android dan hanya mendengarkan Essential Key. Monitor tidak menahan wake lock dan harus dimulai ulang setelah ponsel reboot.", "休眠监视器以 Android shell 权限运行，并且只监听 Essential Key。它不会持有唤醒锁，手机重启后需要重新启动。", "スリープモニターは Android shell 権限で動作し、Essential Key のみを監視します。Wake Lock は保持せず、端末再起動後は再起動が必要です。", "절전 모니터는 Android shell 권한으로 실행되며 Essential Key만 감지합니다. Wake Lock을 유지하지 않으며 휴대폰 재부팅 후 다시 시작해야 합니다."),
    "Sleep monitor is running" to a("Ruhemodus-Monitor läuft", "Le moniteur de veille fonctionne", "Monitor uśpienia działa", "Монітор сну працює", "Monitor tidur berjalan", "休眠监视器正在运行", "スリープモニター実行中", "절전 모니터 실행 중"),
    "Sleep monitor is not running" to a("Ruhemodus-Monitor läuft nicht", "Le moniteur de veille est arrêté", "Monitor uśpienia nie działa", "Монітор сну не запущено", "Monitor tidur tidak berjalan", "休眠监视器未运行", "スリープモニター停止中", "절전 모니터가 실행되지 않음"),
    "Sleep monitor needs restart" to a("Ruhemodus-Monitor muss neu gestartet werden", "Le moniteur de veille doit être redémarré", "Monitor uśpienia wymaga ponownego uruchomienia", "Монітор сну потрібно перезапустити", "Monitor tidur perlu dimulai ulang", "休眠监视器需要重启", "スリープモニターの再起動が必要", "절전 모니터를 다시 시작해야 함"),
    "Required only with the display off" to a("Nur bei ausgeschaltetem Display erforderlich", "Nécessaire uniquement écran éteint", "Wymagane tylko przy wyłączonym ekranie", "Потрібен лише при вимкненому екрані", "Hanya diperlukan saat layar mati", "仅在熄屏时需要", "画面オフ時のみ必要", "화면이 꺼졌을 때만 필요"),
    "INSTALL SLEEP MONITOR" to a("RUHEMODUS-MONITOR INSTALLIEREN", "INSTALLER LE MONITEUR DE VEILLE", "ZAINSTALUJ MONITOR UŚPIENIA", "ВСТАНОВИТИ МОНІТОР СНУ", "PASANG MONITOR TIDUR", "安装休眠监视器", "スリープモニターをインストール", "절전 모니터 설치"),
    "Ready" to a("Bereit", "Prêt", "Gotowe", "Готово", "Siap", "就绪", "準備完了", "준비됨"),
    "Essential Key is ready with the display on and off. After a phone reboot, restart the sleep monitor from Settings." to a("Essential Key ist bei ein- und ausgeschaltetem Display bereit. Starte nach einem Telefonneustart den Ruhemodus-Monitor in den Einstellungen neu.", "Essential Key est prête avec l’écran allumé ou éteint. Après un redémarrage, relancez le moniteur de veille dans les paramètres.", "Essential Key działa przy włączonym i wyłączonym ekranie. Po restarcie telefonu uruchom ponownie monitor uśpienia w ustawieniach.", "Essential Key готова до роботи з увімкненим і вимкненим екраном. Після перезавантаження телефону перезапустіть монітор сну в налаштуваннях.", "Essential Key siap saat layar menyala maupun mati. Setelah ponsel reboot, mulai ulang monitor tidur dari Pengaturan.", "Essential Key 已可在亮屏和熄屏时工作。手机重启后，请在设置中重新启动休眠监视器。", "Essential Key は画面オン・オフの両方で使用できます。端末再起動後は設定からスリープモニターを再起動してください。", "Essential Key를 화면이 켜지거나 꺼진 상태에서 사용할 수 있습니다. 휴대폰 재부팅 후 설정에서 절전 모니터를 다시 시작하세요."),
    "Essential Key is ready while the display is on. You can enable screen-off handling later in Settings." to a("Essential Key ist bei eingeschaltetem Display bereit. Die Funktion bei ausgeschaltetem Display kannst du später in den Einstellungen aktivieren.", "Essential Key est prête lorsque l’écran est allumé. Vous pourrez activer le fonctionnement écran éteint plus tard dans les paramètres.", "Essential Key działa przy włączonym ekranie. Obsługę wyłączonego ekranu możesz później włączyć w ustawieniach.", "Essential Key готова до роботи при увімкненому екрані. Роботу з вимкненим екраном можна увімкнути пізніше в налаштуваннях.", "Essential Key siap saat layar menyala. Dukungan layar mati dapat diaktifkan nanti di Pengaturan.", "Essential Key 已可在亮屏时使用。稍后可在设置中启用熄屏处理。", "Essential Key は画面オン時に使用できます。画面オフ時の動作は後から設定で有効にできます。", "Essential Key를 화면이 켜진 상태에서 사용할 수 있습니다. 화면 꺼짐 처리는 나중에 설정에서 켤 수 있습니다."),
    "Single press" to a("Einmal drücken", "Appui simple", "Pojedyncze naciśnięcie", "Одне натискання", "Tekan sekali", "单击", "1回押し", "한 번 누르기"),
    "Double press" to a("Doppelt drücken", "Double appui", "Podwójne naciśnięcie", "Подвійне натискання", "Tekan dua kali", "双击", "2回押し", "두 번 누르기"),
    "Long press" to a("Gedrückt halten", "Appui long", "Długie naciśnięcie", "Утримання", "Tekan lama", "长按", "長押し", "길게 누르기"),
    "Press and hold" to a("Drücken und halten", "Maintenir appuyé", "Naciśnij i przytrzymaj", "Натиснути й утримувати", "Tekan dan tahan", "按住", "押し続ける", "누르고 있기"),
    "Voice assistant" to a("Sprachassistent", "Assistant vocal", "Asystent głosowy", "Голосовий помічник", "Asisten suara", "语音助手", "音声アシスタント", "음성 어시스턴트"),
    "Flashlight" to a("Taschenlampe", "Lampe torche", "Latarka", "Ліхтарик", "Senter", "手电筒", "ライト", "손전등"),
    "6-digit pairing code" to a("6-stelliger Kopplungscode", "Code d’association à 6 chiffres", "6-cyfrowy kod parowania", "6-значний код сполучення", "Kode penyandingan 6 digit", "6 位配对码", "6桁のペアリングコード", "6자리 페어링 코드"),
    "SUBMIT CODE" to a("CODE BESTÄTIGEN", "VALIDER LE CODE", "ZATWIERDŹ KOD", "ПІДТВЕРДИТИ КОД", "KIRIM KODE", "提交代码", "コードを送信", "코드 제출"),
    "Cancel" to a("Abbrechen", "Annuler", "Anuluj", "Скасувати", "Batal", "取消", "キャンセル", "취소"),
    "Copy the log if the problem repeats." to a("Kopiere das Protokoll, falls das Problem erneut auftritt.", "Copiez le journal si le problème se reproduit.", "Skopiuj log, jeśli problem się powtórzy.", "Скопіюйте лог, якщо проблема повториться.", "Salin log jika masalah terjadi lagi.", "如果问题再次出现，请复制日志。", "問題が再発する場合はログをコピーしてください。", "문제가 반복되면 로그를 복사하세요."),
    "COPY LOG" to a("PROTOKOLL KOPIEREN", "COPIER LE JOURNAL", "KOPIUJ LOG", "КОПІЮВАТИ ЛОГ", "SALIN LOG", "复制日志", "ログをコピー", "로그 복사"),
    "CLEAR LOG" to a("PROTOKOLL LÖSCHEN", "EFFACER LE JOURNAL", "WYCZYŚĆ LOG", "ОЧИСТИТИ ЛОГ", "HAPUS LOG", "清除日志", "ログを消去", "로그 지우기"),
    "Log cleared" to a("Protokoll gelöscht", "Journal effacé", "Log wyczyszczony", "Лог очищено", "Log dihapus", "日志已清除", "ログを消去しました", "로그를 지웠습니다"),
    "Manual ADB commands" to a("Manuelle ADB-Befehle", "Commandes ADB manuelles", "Ręczne polecenia ADB", "Команди ADB вручну", "Perintah ADB manual", "手动 ADB 命令", "手動 ADB コマンド", "수동 ADB 명령"),
    "COPY" to a("KOPIEREN", "COPIER", "KOPIUJ", "КОПІЮВАТИ", "SALIN", "复制", "コピー", "복사"),
    "SAVE CHANGES" to a("ÄNDERUNGEN SPEICHERN", "ENREGISTRER", "ZAPISZ ZMIANY", "ЗБЕРЕГТИ ЗМІНИ", "SIMPAN PERUBAHAN", "保存更改", "変更を保存", "변경사항 저장"),
    "ACTIVE" to a("AKTIV", "ACTIF", "AKTYWNE", "АКТИВНО", "AKTIF", "已启用", "有効", "활성"),
    "PAUSED" to a("PAUSIERT", "EN PAUSE", "WSTRZYMANE", "ПРИЗУПИНЕНО", "DIJEDA", "已暂停", "一時停止", "일시중지"),
    "SETUP REQUIRED" to a("EINRICHTUNG NÖTIG", "CONFIGURATION REQUISE", "WYMAGANA KONFIGURACJA", "ПОТРІБНЕ НАЛАШТУВАННЯ", "PERLU PENYIAPAN", "需要设置", "セットアップが必要", "설정 필요"),
    "Settings" to a("Einstellungen", "Paramètres", "Ustawienia", "Налаштування", "Pengaturan", "设置", "設定", "설정"),
    "BUTTON ACTIONS" to a("TASTENAKTIONEN", "ACTIONS DU BOUTON", "AKCJE PRZYCISKU", "ДІЇ КНОПКИ", "AKSI TOMBOL", "按键操作", "ボタン操作", "버튼 동작"),
    "The listener or Nothing package setup is inactive. Open settings to repair it." to a("Der Listener oder die Nothing-Paketeinrichtung ist inaktiv. Öffne die Einstellungen, um das Problem zu beheben.", "L’écouteur ou la configuration des paquets Nothing est inactive. Ouvrez les paramètres pour corriger le problème.", "Nasłuch lub konfiguracja pakietów Nothing jest nieaktywna. Otwórz ustawienia, aby naprawić problem.", "Служба перехоплення або налаштування пакетів Nothing неактивні. Відкрийте налаштування, щоб виправити проблему.", "Pendengar atau penyiapan paket Nothing tidak aktif. Buka Pengaturan untuk memperbaikinya.", "监听服务或 Nothing 软件包设置未启用。请打开设置进行修复。", "リスナーまたは Nothing パッケージ設定が無効です。設定を開いて修正してください。", "리스너 또는 Nothing 패키지 설정이 비활성 상태입니다. 설정을 열어 수정하세요."),
    "Essential Key is still owned by Nothing" to a("Essential Key wird noch von Nothing verwendet", "Essential Key est encore utilisée par Nothing", "Essential Key jest nadal przechwytywany przez Nothing", "Essential Key усе ще перехоплює Nothing", "Essential Key masih digunakan oleh Nothing", "Essential Key 仍由 Nothing 占用", "Essential Key はまだ Nothing が使用しています", "Essential Key를 아직 Nothing이 사용 중입니다"),
    "Release the key in Essential Remap settings." to a("Gib die Taste in den Essential-Remap-Einstellungen frei.", "Libérez le bouton dans les paramètres d’Essential Remap.", "Zwolnij przycisk w ustawieniach Essential Remap.", "Звільніть кнопку в налаштуваннях Essential Remap.", "Lepaskan tombol di pengaturan Essential Remap.", "请在 Essential Remap 设置中释放按键。", "Essential Remap の設定でボタンを解放してください。", "Essential Remap 설정에서 버튼을 해제하세요."),
    "Another key remapper is active" to a("Ein anderer Tasten-Remapper ist aktiv", "Un autre remappeur de touches est actif", "Aktywny jest inny remapper przycisków", "Активний інший перепризначувач кнопок", "Aplikasi pemetaan tombol lain aktif", "另一个按键映射应用正在运行", "別のキーリマップアプリが有効です", "다른 키 리매퍼가 활성화되어 있습니다"),
    "Disable the competing key service in Accessibility settings." to a("Deaktiviere den konkurrierenden Dienst in den Bedienungshilfe-Einstellungen.", "Désactivez le service concurrent dans les paramètres d’accessibilité.", "Wyłącz konkurencyjną usługę w ustawieniach ułatwień dostępu.", "Вимкніть конкуруючу службу в налаштуваннях спеціальних можливостей.", "Nonaktifkan layanan tombol yang bersaing di pengaturan Aksesibilitas.", "请在无障碍设置中关闭冲突的按键服务。", "ユーザー補助設定で競合するキーサービスを無効にしてください。", "접근성 설정에서 충돌하는 키 서비스를 꺼 주세요."),
    "FIX" to a("BEHEBEN", "CORRIGER", "NAPRAW", "ВИПРАВИТИ", "PERBAIKI", "修复", "修正", "수정"),
    "Run while locked" to a("Bei Sperrbildschirm ausführen", "Exécuter sur écran verrouillé", "Działaj na blokadzie", "Працювати на блокуванні", "Jalankan saat terkunci", "锁屏时运行", "ロック中も実行", "잠금 상태에서 실행"),
    "Lock screen and display off" to a("Sperrbildschirm und Display aus", "Écran verrouillé et écran éteint", "Ekran blokady i wyłączony ekran", "Екран блокування та вимкнений екран", "Layar terkunci dan layar mati", "锁屏和熄屏", "ロック画面と画面オフ", "잠금 화면 및 화면 꺼짐"),
    "While the lock screen is visible" to a("Solange der Sperrbildschirm sichtbar ist", "Lorsque l’écran de verrouillage est visible", "Gdy ekran blokady jest widoczny", "Поки видно екран блокування", "Saat layar kunci terlihat", "锁屏界面可见时", "ロック画面が表示されている間", "잠금 화면이 표시되는 동안"),
    "HAPTIC FEEDBACK" to a("HAPTISCHES FEEDBACK", "RETOUR HAPTIQUE", "REAKCJA HAPTYCZNA", "ТАКТИЛЬНИЙ ВІДГУК", "UMPAN BALIK HAPTIK", "触觉反馈", "触覚フィードバック", "햅틱 피드백"),
    "Launch an app" to a("App starten", "Lancer une application", "Uruchom aplikację", "Запустити застосунок", "Buka aplikasi", "启动应用", "アプリを起動", "앱 실행"),
    "Google + Hold handle to search" to a("Google + Navigationsleiste gedrückt halten", "Google + maintenir la barre de navigation", "Google + przytrzymanie paska nawigacji", "Google + утримання панелі навігації", "Google + tahan bilah navigasi untuk mencari", "Google + 长按导航条搜索", "Google + ナビゲーションバー長押し", "Google + 탐색 바 길게 누르기"),
    "Take screenshot" to a("Screenshot erstellen", "Faire une capture d’écran", "Zrób zrzut ekranu", "Знімок екрана", "Ambil tangkapan layar", "截屏", "スクリーンショット", "스크린샷"),
    "Open camera" to a("Kamera öffnen", "Ouvrir l’appareil photo", "Otwórz aparat", "Відкрити камеру", "Buka kamera", "打开相机", "カメラを開く", "카메라 열기"),
    "Camera" to a("Kamera", "Appareil photo", "Aparat", "Камера", "Kamera", "相机", "カメラ", "카메라"),
    "Notifications" to a("Benachrichtigungen", "Notifications", "Powiadomienia", "Сповіщення", "Notifikasi", "通知", "通知", "알림"),
    "Quick Settings" to a("Schnelleinstellungen", "Réglages rapides", "Szybkie ustawienia", "Швидкі налаштування", "Setelan Cepat", "快捷设置", "クイック設定", "빠른 설정"),
    "Lock screen" to a("Bildschirm sperren", "Verrouiller l’écran", "Zablokuj ekran", "Заблокувати екран", "Kunci layar", "锁定屏幕", "画面をロック", "화면 잠금"),
    "Power menu" to a("Ein/Aus-Menü", "Menu d’alimentation", "Menu zasilania", "Меню живлення", "Menu daya", "电源菜单", "電源メニュー", "전원 메뉴"),
    "Sound mode" to a("Tonmodus", "Mode sonore", "Tryb dźwięku", "Режим звуку", "Mode suara", "声音模式", "サウンドモード", "소리 모드"),
    "Play / pause media" to a("Medien abspielen / pausieren", "Lecture / pause", "Odtwarzaj / pauza", "Відтворення / пауза", "Putar / jeda media", "播放 / 暂停媒体", "再生 / 一時停止", "재생 / 일시정지"),
    "Play / pause" to a("Abspielen / pausieren", "Lecture / pause", "Odtwarzaj / pauza", "Відтворення / пауза", "Putar / jeda", "播放 / 暂停", "再生 / 一時停止", "재생 / 일시정지"),
    "Next track" to a("Nächster Titel", "Piste suivante", "Następny utwór", "Наступний трек", "Lagu berikutnya", "下一曲", "次の曲", "다음 곡"),
    "Previous track" to a("Vorheriger Titel", "Piste précédente", "Poprzedni utwór", "Попередній трек", "Lagu sebelumnya", "上一曲", "前の曲", "이전 곡"),
    "Back" to a("Zurück", "Retour", "Wstecz", "Назад", "Kembali", "返回", "戻る", "뒤로"),
    "Home" to a("Startseite", "Accueil", "Ekran główny", "Головний екран", "Beranda", "主屏幕", "ホーム", "홈"),
    "Recent apps" to a("Letzte Apps", "Applications récentes", "Ostatnie aplikacje", "Недавні застосунки", "Aplikasi terbaru", "最近任务", "最近のアプリ", "최근 앱"),
    "Open link / deep link" to a("Link / Deep Link öffnen", "Ouvrir un lien / deep link", "Otwórz link / deep link", "Відкрити посилання / deep link", "Buka tautan / deep link", "打开链接 / 深层链接", "リンク / ディープリンクを開く", "링크 / 딥링크 열기"),
    "HTTP request" to a("HTTP-Anfrage", "Requête HTTP", "Żądanie HTTP", "HTTP-запит", "Permintaan HTTP", "HTTP 请求", "HTTP リクエスト", "HTTP 요청"),
    "For Tasker, Home Assistant and webhooks" to a("Für Tasker, Home Assistant und Webhooks", "Pour Tasker, Home Assistant et les webhooks", "Dla Tasker, Home Assistant i webhooków", "Для Tasker, Home Assistant і вебхуків", "Untuk Tasker, Home Assistant, dan webhook", "用于 Tasker、Home Assistant 和 Webhook", "Tasker、Home Assistant、Webhook 用", "Tasker, Home Assistant 및 웹훅용"),
    "No action" to a("Keine Aktion", "Aucune action", "Brak akcji", "Нічого", "Tidak ada aksi", "无操作", "何もしない", "동작 없음"),
    "Choose action" to a("Aktion wählen", "Choisir une action", "Wybierz akcję", "Оберіть дію", "Pilih aksi", "选择操作", "操作を選択", "동작 선택"),
    "Choose app" to a("App wählen", "Choisir une application", "Wybierz aplikację", "Оберіть застосунок", "Pilih aplikasi", "选择应用", "アプリを選択", "앱 선택"),
    "Choose an app" to a("App auswählen", "Choisir une application", "Wybierz aplikację", "Оберіть застосунок", "Pilih aplikasi", "选择应用", "アプリを選択", "앱 선택"),
    "Search" to a("Suchen", "Rechercher", "Szukaj", "Пошук", "Cari", "搜索", "検索", "검색"),
    "Open link" to a("Link öffnen", "Ouvrir un lien", "Otwórz link", "Відкрити посилання", "Buka tautan", "打开链接", "リンクを開く", "링크 열기"),
    "APPLY" to a("ANWENDEN", "APPLIQUER", "ZASTOSUJ", "ЗАСТОСУВАТИ", "TERAPKAN", "应用", "適用", "적용"),
    "Base URL" to a("Basis-URL", "URL de base", "Bazowy URL", "Базовий URL", "URL dasar", "基础 URL", "ベース URL", "기본 URL"),
    "Path or full URL" to a("Pfad oder vollständige URL", "Chemin ou URL complète", "Ścieżka lub pełny URL", "Шлях або повний URL", "Path atau URL lengkap", "路径或完整 URL", "パスまたは完全な URL", "경로 또는 전체 URL"),
    "request" to a("Anfrage", "requête", "żądanie", "запит", "permintaan", "请求", "リクエスト", "요청"),
    "KEY STATUS" to a("TASTENSTATUS", "ÉTAT DU BOUTON", "STAN PRZYCISKU", "СТАН КНОПКИ", "STATUS TOMBOL", "按键状态", "ボタンの状態", "버튼 상태"),
    "Required with the display off; restart after every phone reboot" to a("Bei ausgeschaltetem Display erforderlich; nach jedem Neustart neu starten", "Nécessaire écran éteint ; redémarrer après chaque redémarrage", "Wymagane przy wyłączonym ekranie; uruchom ponownie po każdym restarcie telefonu", "Потрібен при вимкненому екрані; перезапускайте після кожного перезавантаження", "Diperlukan saat layar mati; mulai ulang setelah setiap reboot", "熄屏时需要；每次手机重启后请重新启动", "画面オフ時に必要。端末再起動後は毎回再起動してください", "화면이 꺼졌을 때 필요하며 휴대폰 재부팅 후 매번 다시 시작해야 합니다"),
    "RESTORE" to a("WIEDERHERSTELLEN", "RESTAURER", "PRZYWRÓĆ", "ВІДНОВИТИ", "PULIHKAN", "恢复", "復元", "복원"),
    "RESTART" to a("NEUSTART", "REDÉMARRER", "URUCHOM PONOWNIE", "ПЕРЕЗАПУСТИТИ", "MULAI ULANG", "重新启动", "再起動", "다시 시작"),
    "START" to a("STARTEN", "DÉMARRER", "URUCHOM", "ЗАПУСТИТИ", "MULAI", "启动", "開始", "시작"),
    "BUTTON" to a("TASTE", "BOUTON", "PRZYCISK", "КНОПКА", "TOMBOL", "按键", "ボタン", "버튼"),
    "Handle Essential Key" to a("Essential Key verarbeiten", "Gérer Essential Key", "Obsługuj Essential Key", "Обробляти Essential Key", "Tangani Essential Key", "处理 Essential Key", "Essential Key を処理", "Essential Key 처리"),
    "Configured actions are active" to a("Konfigurierte Aktionen sind aktiv", "Les actions configurées sont actives", "Skonfigurowane akcje są aktywne", "Призначені дії активні", "Aksi yang dikonfigurasi aktif", "已启用配置的操作", "設定した操作は有効です", "설정된 동작이 활성화되어 있습니다"),
    "Button actions are paused" to a("Tastenaktionen sind pausiert", "Les actions du bouton sont en pause", "Akcje przycisku są wstrzymane", "Дії кнопки призупинено", "Aksi tombol dijeda", "按键操作已暂停", "ボタン操作は一時停止中", "버튼 동작이 일시중지되었습니다"),
    "Work with screen off" to a("Bei ausgeschaltetem Display arbeiten", "Fonctionner écran éteint", "Działaj przy wyłączonym ekranie", "Працювати з вимкненим екраном", "Bekerja saat layar mati", "熄屏时工作", "画面オフ時も動作", "화면 꺼짐 상태에서 동작"),
    "Uses the sleep monitor; restart it after a phone reboot" to a("Verwendet den Ruhemodus-Monitor; nach einem Neustart neu starten", "Utilise le moniteur de veille ; redémarrez-le après un redémarrage", "Używa monitora uśpienia; uruchom go ponownie po restarcie telefonu", "Використовує монітор сну; після перезавантаження телефону його потрібно перезапустити", "Menggunakan monitor tidur; mulai ulang setelah ponsel reboot", "使用休眠监视器；手机重启后需要重新启动", "スリープモニターを使用します。端末再起動後は再起動してください", "절전 모니터를 사용합니다. 휴대폰 재부팅 후 다시 시작하세요"),
    "Only while the display is on" to a("Nur bei eingeschaltetem Display", "Uniquement lorsque l’écran est allumé", "Tylko przy włączonym ekranie", "Лише при увімкненому екрані", "Hanya saat layar menyala", "仅亮屏时", "画面オン時のみ", "화면이 켜졌을 때만"),
    "PERMISSIONS" to a("BERECHTIGUNGEN", "AUTORISATIONS", "UPRAWNIENIA", "ДОЗВОЛИ", "IZIN", "权限", "権限", "권한"),
    "Accessibility" to a("Bedienungshilfe", "Accessibilité", "Ułatwienia dostępu", "Спеціальні можливості", "Aksesibilitas", "无障碍", "ユーザー補助", "접근성"),
    "Enabled" to a("Aktiviert", "Activé", "Włączone", "Увімкнено", "Aktif", "已启用", "有効", "켜짐"),
    "Disabled" to a("Deaktiviert", "Désactivé", "Wyłączone", "Вимкнено", "Nonaktif", "已关闭", "無効", "꺼짐"),
    "Default assistant" to a("Standardassistent", "Assistant par défaut", "Domyślny asystent", "Помічник за замовчуванням", "Asisten default", "默认助手", "デフォルトのアシスタント", "기본 어시스턴트"),
    "Do Not Disturb access" to a("Zugriff auf Nicht stören", "Accès Ne pas déranger", "Dostęp do Nie przeszkadzać", "Доступ до «Не турбувати»", "Akses Jangan Ganggu", "勿扰权限", "サイレントモードへのアクセス", "방해 금지 접근 권한"),
    "Only needed for Silent mode" to a("Nur für Lautlos-Modus erforderlich", "Nécessaire uniquement pour le mode silencieux", "Potrzebne tylko dla trybu cichego", "Потрібен лише для беззвучного режиму", "Hanya diperlukan untuk mode senyap", "仅静音模式需要", "サイレントモードにのみ必要", "무음 모드에만 필요"),
    "LANGUAGE" to a("SPRACHE", "LANGUE", "JĘZYK", "МОВА", "BAHASA", "语言", "言語", "언어"),
    "APP" to a("APP", "APPLICATION", "APLIKACJA", "ЗАСТОСУНОК", "APLIKASI", "应用", "アプリ", "앱"),
    "Run setup again" to a("Einrichtung wiederholen", "Recommencer la configuration", "Uruchom konfigurację ponownie", "Повторити початкове налаштування", "Ulangi penyiapan", "重新运行设置", "セットアップをやり直す", "설정 다시 실행"),
    "Android app info" to a("Android-App-Info", "Infos de l’application Android", "Informacje o aplikacji", "Інформація про застосунок", "Info aplikasi Android", "Android 应用信息", "Android アプリ情報", "Android 앱 정보"),
    "Check for updates" to a("Nach Updates suchen", "Rechercher les mises à jour", "Sprawdź aktualizacje", "Перевірити оновлення", "Periksa pembaruan", "检查更新", "アップデートを確認", "업데이트 확인"),
    "Latest version installed" to a("Neueste Version ist installiert", "La dernière version est installée", "Masz najnowszą wersję", "Встановлено найновішу версію", "Versi terbaru sudah terpasang", "已安装最新版本", "最新バージョンです", "최신 버전이 설치되어 있습니다"),
    "Could not check for updates" to a("Updates konnten nicht geprüft werden", "Impossible de rechercher les mises à jour", "Nie udało się sprawdzić aktualizacji", "Не вдалося перевірити оновлення", "Tidak dapat memeriksa pembaruan", "无法检查更新", "アップデートを確認できませんでした", "업데이트를 확인할 수 없습니다"),
    "Restore Essential Space before uninstalling Essential Remap. Uninstalling the APK alone does not re-enable Nothing's components." to a("Stelle Essential Space wieder her, bevor du Essential Remap deinstallierst. Das Entfernen der APK allein aktiviert die Nothing-Komponenten nicht erneut.", "Restaurez Essential Space avant de désinstaller Essential Remap. La suppression de l’APK seule ne réactive pas les composants Nothing.", "Przywróć Essential Space przed odinstalowaniem Essential Remap. Samo usunięcie APK nie włączy ponownie komponentów Nothing.", "Відновіть Essential Space перед видаленням Essential Remap. Просте видалення APK не ввімкне компоненти Nothing назад.", "Pulihkan Essential Space sebelum menghapus Essential Remap. Menghapus APK saja tidak akan mengaktifkan kembali komponen Nothing.", "卸载 Essential Remap 前请先恢复 Essential Space。仅删除 APK 不会重新启用 Nothing 组件。", "Essential Remap をアンインストールする前に Essential Space を復元してください。APK を削除するだけでは Nothing のコンポーネントは再有効化されません。", "Essential Remap을 삭제하기 전에 Essential Space를 복원하세요. APK만 삭제하면 Nothing 구성요소가 다시 활성화되지 않습니다."),
    "Donate" to a("Spenden", "Faire un don", "Wesprzyj", "Підтримати", "Donasi", "赞助", "寄付", "후원"),
    "Toggle silent / normal" to a("Lautlos / Normal umschalten", "Basculer silencieux / normal", "Przełącz cichy / normalny", "Без звуку / звичайний", "Alihkan senyap / normal", "静音 / 正常切换", "サイレント / 通常を切替", "무음 / 일반 전환"),
    "Normal" to a("Normal", "Normal", "Normalny", "Звичайний", "Normal", "正常", "通常", "일반"),
    "Vibrate" to a("Vibrieren", "Vibreur", "Wibracje", "Вібрація", "Getar", "振动", "バイブ", "진동"),
    "Silent" to a("Lautlos", "Silencieux", "Cichy", "Без звуку", "Senyap", "静音", "サイレント", "무음"),
    "Off" to a("Aus", "Désactivé", "Wył.", "Вимк.", "Mati", "关闭", "オフ", "끔"),
    "Light" to a("Leicht", "Léger", "Lekki", "Слабкий", "Ringan", "轻", "弱", "약하게"),
    "Medium" to a("Mittel", "Moyen", "Średni", "Середній", "Sedang", "中", "中", "보통"),
    "Strong" to a("Stark", "Fort", "Mocny", "Сильний", "Kuat", "强", "強", "강하게"),
    "Essential Key is released" to a("Essential Key ist freigegeben", "Essential Key est libérée", "Essential Key jest zwolniony", "Essential Key звільнено", "Essential Key sudah dilepas", "Essential Key 已释放", "Essential Key は解放済み", "Essential Key 해제됨"),
    "Essential Space owns the key" to a("Essential Space verwendet die Taste", "Essential Space utilise le bouton", "Essential Space przechwytuje przycisk", "Кнопку перехоплює Essential Space", "Essential Space menggunakan tombol", "Essential Space 正在占用按键", "Essential Space がボタンを使用中", "Essential Space가 버튼을 사용 중"),
    "Only partially released" to a("Nur teilweise freigegeben", "Libération partielle", "Przycisk zwolniony częściowo", "Кнопку звільнено частково", "Tombol baru dilepas sebagian", "仅部分释放", "一部のみ解放済み", "일부만 해제됨"),
    "Nothing packages not found" to a("Nothing-Pakete nicht gefunden", "Paquets Nothing introuvables", "Nie znaleziono pakietów Nothing", "Пакети Nothing не знайдено", "Paket Nothing tidak ditemukan", "未找到 Nothing 软件包", "Nothing パッケージが見つかりません", "Nothing 패키지를 찾을 수 없음"),
    "Checking package status" to a("Paketstatus wird geprüft", "Vérification des paquets", "Sprawdzanie pakietów", "Перевірка пакетів", "Memeriksa status paket", "正在检查软件包状态", "パッケージ状態を確認中", "패키지 상태 확인 중"),
    "Finding Wireless ADB" to a("Wireless ADB wird gesucht", "Recherche de Wireless ADB", "Wyszukiwanie Wireless ADB", "Пошук Wireless ADB", "Mencari Wireless ADB", "正在查找 Wireless ADB", "Wireless ADB を検索中", "Wireless ADB 찾는 중"),
    "Enable Wireless debugging" to a("Wireless-Debugging aktivieren", "Activez le débogage sans fil", "Włącz debugowanie bezprzewodowe", "Увімкніть Wireless debugging", "Aktifkan Wireless debugging", "启用无线调试", "ワイヤレスデバッグを有効化", "무선 디버깅 켜기"),
    "Enter the pairing code" to a("Kopplungscode eingeben", "Saisissez le code d’association", "Wprowadź kod parowania", "Введіть код сполучення", "Masukkan kode penyandingan", "输入配对码", "ペアリングコードを入力", "페어링 코드 입력"),
    "Pairing with Android" to a("Kopplung mit Android", "Association avec Android", "Parowanie z Androidem", "Сполучення з Android", "Menyandingkan dengan Android", "正在与 Android 配对", "Android とペアリング中", "Android와 페어링 중"),
    "Connecting" to a("Verbindung wird hergestellt", "Connexion", "Łączenie", "Підключення", "Menghubungkan", "正在连接", "接続中", "연결 중"),
    "Applying package state" to a("Paketstatus wird angewendet", "Application de l’état des paquets", "Stosowanie ustawień pakietów", "Застосування стану пакетів", "Menerapkan status paket", "正在应用软件包状态", "パッケージ状態を適用中", "패키지 상태 적용 중"),
    "Setup complete" to a("Einrichtung abgeschlossen", "Configuration terminée", "Konfiguracja zakończona", "Налаштування завершено", "Penyiapan selesai", "设置完成", "セットアップ完了", "설정 완료"),
    "Setup failed" to a("Einrichtung fehlgeschlagen", "Échec de la configuration", "Błąd konfiguracji", "Помилка налаштування", "Penyiapan gagal", "设置失败", "セットアップ失敗", "설정 실패"),
    "Support Essential Remap" to a("Essential Remap unterstützen", "Soutenir Essential Remap", "Wesprzyj Essential Remap", "Підтримати Essential Remap", "Dukung Essential Remap", "支持 Essential Remap", "Essential Remap を支援", "Essential Remap 후원"),
    "The app stays free and open-source. If it is useful, you can support further development." to a("Die App bleibt kostenlos und Open Source. Wenn sie dir hilft, kannst du die weitere Entwicklung unterstützen.", "L’application reste gratuite et open source. Si elle vous est utile, vous pouvez soutenir son développement.", "Aplikacja pozostaje darmowa i open source. Jeśli jest przydatna, możesz wesprzeć jej dalszy rozwój.", "Застосунок залишається безкоштовним і open-source. Якщо він корисний, ви можете підтримати подальшу розробку.", "Aplikasi tetap gratis dan open-source. Jika bermanfaat, Anda dapat mendukung pengembangannya.", "应用将始终免费且开源。如果它对你有帮助，可以支持后续开发。", "アプリは無料かつオープンソースのままです。役に立った場合は開発を支援できます。", "앱은 계속 무료 오픈소스로 제공됩니다. 유용하다면 개발을 후원할 수 있습니다."),
    "NOT NOW" to a("NICHT JETZT", "PAS MAINTENANT", "NIE TERAZ", "НЕ ЗАРАЗ", "NANTI", "暂不", "後で", "나중에"),
    "SUPPORT" to a("UNTERSTÜTZEN", "SOUTENIR", "WESPRZYJ", "ПІДТРИМАТИ", "DUKUNG", "支持", "支援する", "후원"),
    "LATER" to a("SPÄTER", "PLUS TARD", "PÓŹNIEJ", "ПІЗНІШЕ", "NANTI", "稍后", "後で", "나중에"),
    "DOWNLOAD" to a("HERUNTERLADEN", "TÉLÉCHARGER", "POBIERZ", "ЗАВАНТАЖИТИ", "UNDUH", "下载", "ダウンロード", "다운로드"),
    "Downloading update" to a("Update wird heruntergeladen", "Téléchargement de la mise à jour", "Pobieranie aktualizacji", "Завантаження оновлення", "Mengunduh pembaruan", "正在下载更新", "アップデートをダウンロード中", "업데이트 다운로드 중"),
    "Downloading…" to a("Wird heruntergeladen…", "Téléchargement…", "Pobieranie…", "Завантаження…", "Mengunduh…", "正在下载…", "ダウンロード中…", "다운로드 중…"),
    "Update downloaded" to a("Update heruntergeladen", "Mise à jour téléchargée", "Aktualizacja pobrana", "Оновлення завантажено", "Pembaruan telah diunduh", "更新已下载", "アップデートをダウンロードしました", "업데이트 다운로드 완료"),
    "Android will ask you to confirm the installation." to a("Android bittet dich, die Installation zu bestätigen.", "Android vous demandera de confirmer l’installation.", "Android poprosi o potwierdzenie instalacji.", "Android попросить підтвердити встановлення.", "Android akan meminta konfirmasi pemasangan.", "Android 会要求你确认安装。", "Android がインストールの確認を求めます。", "Android에서 설치 확인을 요청합니다."),
    "INSTALL" to a("INSTALLIEREN", "INSTALLER", "ZAINSTALUJ", "ВСТАНОВИТИ", "PASANG", "安装", "インストール", "설치"),
    "Download failed" to a("Download fehlgeschlagen", "Échec du téléchargement", "Pobieranie nie powiodło się", "Не вдалося завантажити", "Unduhan gagal", "下载失败", "ダウンロード失敗", "다운로드 실패"),
    "Check your connection and try again. The APK is also verified before installation." to a("Prüfe deine Verbindung und versuche es erneut. Die APK wird vor der Installation ebenfalls überprüft.", "Vérifiez votre connexion et réessayez. L’APK est également vérifié avant l’installation.", "Sprawdź połączenie i spróbuj ponownie. APK jest również weryfikowany przed instalacją.", "Перевірте з’єднання та спробуйте ще раз. APK також перевіряється перед встановленням.", "Periksa koneksi lalu coba lagi. APK juga diverifikasi sebelum dipasang.", "请检查网络后重试。安装前还会验证 APK。", "接続を確認して再試行してください。APK はインストール前にも検証されます。", "연결을 확인하고 다시 시도하세요. 설치 전 APK도 검증합니다."),
    "CLOSE" to a("SCHLIESSEN", "FERMER", "ZAMKNIJ", "ЗАКРИТИ", "TUTUP", "关闭", "閉じる", "닫기"),
    "RETRY" to a("ERNEUT VERSUCHEN", "RÉESSAYER", "PONÓW", "ПОВТОРИТИ", "COBA LAGI", "重试", "再試行", "다시 시도"),
    "Without notifications, enter a pairing code after returning to the app" to a("Ohne Benachrichtigungen musst du den Kopplungscode nach der Rückkehr zur App eingeben", "Sans notifications, saisissez le code d’association après être revenu dans l’application", "Bez powiadomień wpisz kod parowania po powrocie do aplikacji", "Без сповіщень введіть код сполучення після повернення до застосунку", "Tanpa notifikasi, masukkan kode penyandingan setelah kembali ke aplikasi", "若不允许通知，请返回应用后输入配对码", "通知を許可しない場合はアプリに戻ってからペアリングコードを入力してください", "알림을 허용하지 않으면 앱으로 돌아온 뒤 페어링 코드를 입력하세요"),
    "Could not open the Android package installer" to a("Android-Paketinstaller konnte nicht geöffnet werden", "Impossible d’ouvrir le programme d’installation Android", "Nie udało się otworzyć instalatora Android", "Не вдалося відкрити інсталятор Android", "Tidak dapat membuka pemasang paket Android", "无法打开 Android 安装程序", "Android のパッケージインストーラを開けませんでした", "Android 패키지 설치 프로그램을 열 수 없습니다"),
    "Copied" to a("Kopiert", "Copié", "Skopiowano", "Скопійовано", "Disalin", "已复制", "コピーしました", "복사됨"),
    "Connecting to Wireless debugging…" to a("Verbindung mit Wireless-Debugging…", "Connexion au débogage sans fil…", "Łączenie z debugowaniem bezprzewodowym…", "Підключення до Wireless debugging…", "Menghubungkan ke Wireless debugging…", "正在连接无线调试…", "ワイヤレスデバッグに接続中…", "무선 디버깅에 연결 중…"),
    "Pairing code must contain six digits" to a("Der Kopplungscode muss sechs Ziffern enthalten", "Le code d’association doit contenir six chiffres", "Kod parowania musi mieć sześć cyfr", "Код сполучення має містити шість цифр", "Kode penyandingan harus berisi enam digit", "配对码必须为 6 位数字", "ペアリングコードは6桁である必要があります", "페어링 코드는 6자리 숫자여야 합니다"),
    "Pairing code received. Completing setup…" to a("Kopplungscode erhalten. Einrichtung wird abgeschlossen…", "Code reçu. Finalisation de la configuration…", "Kod odebrany. Kończenie konfiguracji…", "Код отримано. Завершуємо налаштування…", "Kode diterima. Menyelesaikan penyiapan…", "已收到配对码，正在完成设置…", "コードを受信しました。セットアップを完了しています…", "코드를 받았습니다. 설정을 완료하는 중…"),
    "Turn on Wireless debugging. Essential Remap will reconnect automatically." to a("Aktiviere Wireless-Debugging. Essential Remap verbindet sich automatisch erneut.", "Activez le débogage sans fil. Essential Remap se reconnectera automatiquement.", "Włącz debugowanie bezprzewodowe. Essential Remap połączy się automatycznie.", "Увімкніть Wireless debugging. Essential Remap підключиться автоматично.", "Aktifkan Wireless debugging. Essential Remap akan tersambung kembali otomatis.", "请开启无线调试，Essential Remap 会自动重新连接。", "ワイヤレスデバッグをオンにすると Essential Remap が自動で再接続します。", "무선 디버깅을 켜면 Essential Remap이 자동으로 다시 연결됩니다."),
    "Releasing Essential Key" to a("Essential Key wird freigegeben", "Libération de Essential Key", "Zwalnianie Essential Key", "Звільняємо Essential Key", "Melepaskan Essential Key", "正在释放 Essential Key", "Essential Key を解放中", "Essential Key 해제 중"),
    "Starting sleep monitor" to a("Ruhemodus-Monitor wird gestartet", "Démarrage du moniteur de veille", "Uruchamianie monitora uśpienia", "Запускаємо монітор сну", "Memulai monitor tidur", "正在启动休眠监视器", "スリープモニターを起動中", "절전 모니터 시작 중"),
    "Restoring Essential Space" to a("Essential Space wird wiederhergestellt", "Restauration de Essential Space", "Przywracanie Essential Space", "Відновлюємо Essential Space", "Memulihkan Essential Space", "正在恢复 Essential Space", "Essential Space を復元中", "Essential Space 복원 중"),
    "Essential Key released. Wireless debugging can be turned off." to a("Essential Key ist freigegeben. Wireless-Debugging kann ausgeschaltet werden.", "Essential Key est libérée. Vous pouvez désactiver le débogage sans fil.", "Essential Key została zwolniona. Możesz wyłączyć debugowanie bezprzewodowe.", "Essential Key звільнено. Wireless debugging можна вимкнути.", "Essential Key sudah dilepas. Wireless debugging dapat dimatikan.", "Essential Key 已释放，可以关闭无线调试。", "Essential Key を解放しました。ワイヤレスデバッグはオフにできます。", "Essential Key가 해제되었습니다. 무선 디버깅을 꺼도 됩니다."),
    "Sleep monitor started. Wireless debugging can be turned off." to a("Ruhemodus-Monitor gestartet. Wireless-Debugging kann ausgeschaltet werden.", "Moniteur de veille démarré. Vous pouvez désactiver le débogage sans fil.", "Monitor uśpienia uruchomiony. Możesz wyłączyć debugowanie bezprzewodowe.", "Монітор сну запущено. Wireless debugging можна вимкнути.", "Monitor tidur berjalan. Wireless debugging dapat dimatikan.", "休眠监视器已启动，可以关闭无线调试。", "スリープモニターを起動しました。ワイヤレスデバッグはオフにできます。", "절전 모니터가 시작되었습니다. 무선 디버깅을 꺼도 됩니다."),
    "Essential Space restored. Wireless debugging can be turned off." to a("Essential Space wiederhergestellt. Wireless-Debugging kann ausgeschaltet werden.", "Essential Space restauré. Vous pouvez désactiver le débogage sans fil.", "Essential Space przywrócone. Możesz wyłączyć debugowanie bezprzewodowe.", "Essential Space відновлено. Wireless debugging можна вимкнути.", "Essential Space dipulihkan. Wireless debugging dapat dimatikan.", "Essential Space 已恢复，可以关闭无线调试。", "Essential Space を復元しました。ワイヤレスデバッグはオフにできます。", "Essential Space가 복원되었습니다. 무선 디버깅을 꺼도 됩니다."),
    "Essential Remap setup" to a("Essential-Remap-Einrichtung", "Configuration de Essential Remap", "Konfiguracja Essential Remap", "Налаштування Essential Remap", "Penyiapan Essential Remap", "Essential Remap 设置", "Essential Remap セットアップ", "Essential Remap 설정"),
    "Six-digit pairing code" to a("Sechsstelliger Kopplungscode", "Code d’association à six chiffres", "Sześciocyfrowy kod parowania", "Шестизначний код сполучення", "Kode penyandingan enam digit", "6 位配对码", "6桁のペアリングコード", "6자리 페어링 코드"),
    "Enter pairing code" to a("Kopplungscode eingeben", "Saisir le code d’association", "Wpisz kod parowania", "Ввести код сполучення", "Masukkan kode penyandingan", "输入配对码", "ペアリングコードを入力", "페어링 코드 입력"),
    "Wireless debugging setup" to a("Wireless-Debugging-Einrichtung", "Configuration du débogage sans fil", "Konfiguracja debugowania bezprzewodowego", "Налаштування Wireless debugging", "Penyiapan Wireless debugging", "无线调试设置", "ワイヤレスデバッグ設定", "무선 디버깅 설정"),
    "Restart the sleep monitor" to a("Ruhemodus-Monitor neu starten", "Redémarrer le moniteur de veille", "Uruchom ponownie monitor uśpienia", "Перезапустіть монітор сну", "Mulai ulang monitor tidur", "重新启动休眠监视器", "スリープモニターを再起動", "절전 모니터 다시 시작"),
    "Screen-off Essential Key handling must be reactivated after a phone reboot." to a("Die Essential-Key-Funktion bei ausgeschaltetem Display muss nach einem Neustart erneut aktiviert werden.", "La gestion de Essential Key écran éteint doit être réactivée après un redémarrage.", "Obsługę Essential Key przy wyłączonym ekranie trzeba ponownie aktywować po restarcie telefonu.", "Роботу Essential Key з вимкненим екраном потрібно повторно активувати після перезавантаження телефону.", "Penanganan Essential Key saat layar mati harus diaktifkan kembali setelah ponsel reboot.", "手机重启后需要重新启用熄屏 Essential Key 功能。", "端末再起動後は画面オフ時の Essential Key を再有効化する必要があります。", "휴대폰 재부팅 후 화면 꺼짐 Essential Key 기능을 다시 활성화해야 합니다."),
    "Open Essential Remap, enable Wireless debugging, then tap Restart for the sleep monitor." to a("Öffne Essential Remap, aktiviere Wireless-Debugging und tippe beim Ruhemodus-Monitor auf Neustart.", "Ouvrez Essential Remap, activez le débogage sans fil puis appuyez sur Redémarrer pour le moniteur de veille.", "Otwórz Essential Remap, włącz debugowanie bezprzewodowe i naciśnij Uruchom ponownie przy monitorze uśpienia.", "Відкрийте Essential Remap, увімкніть Wireless debugging і натисніть «Перезапустити» для монітора сну.", "Buka Essential Remap, aktifkan Wireless debugging, lalu ketuk Mulai ulang pada monitor tidur.", "打开 Essential Remap，启用无线调试，然后点击休眠监视器的“重新启动”。", "Essential Remap を開き、ワイヤレスデバッグを有効にしてからスリープモニターの「再起動」をタップしてください。", "Essential Remap을 열고 무선 디버깅을 켠 다음 절전 모니터의 다시 시작을 누르세요.")
)
